[workspace]
members = [
  "crates/melody_cli",
  "crates/melody_compiler",
  "crates/melody_wasm",
  "xtask",
]
edition = "2021"

[profile.release]
strip = true

[profile.release.package.melody_wasm]
opt-level = "z"
strip = true
codegen-units = 1
